// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHq9qPa0vB5hN2au1-04s3l4bqKqGsuvg',
    appId: '1:1065333818789:web:99e77a7306c22735e6944c',
    messagingSenderId: '1065333818789',
    projectId: 'sfac-test-2c60c',
    authDomain: 'sfac-test-2c60c.firebaseapp.com',
    storageBucket: 'sfac-test-2c60c.appspot.com',
    measurementId: 'G-G8Z89WKZL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7X8F9XCadY-VAAnsi6CDhIGBws_n4uJs',
    appId: '1:1065333818789:android:0b4fbf560d502941e6944c',
    messagingSenderId: '1065333818789',
    projectId: 'sfac-test-2c60c',
    storageBucket: 'sfac-test-2c60c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZPEYX_5_-PXEKNhxntEQ7fVoB2tPCIw',
    appId: '1:1065333818789:ios:473bb56d8b43fcc9e6944c',
    messagingSenderId: '1065333818789',
    projectId: 'sfac-test-2c60c',
    storageBucket: 'sfac-test-2c60c.appspot.com',
    iosBundleId: 'com.example.firebaseCrudPrac',
  );
}
